import { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export async function getStaticProps() {
  async function fetchData() {
    const data = await fetch('https://jsonplaceholder.typicode.com/posts');
    return await data.json();
  }

  const posts = await fetchData();

  return {
    props: { posts },
  };
}

const Home: NextPage = ({ posts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>LNL: Next.js Fundamentals</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the{' '}
          <a href='https://nextjs.org'>Next.js Fundamentals LNL</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div>
          <h2>Posts</h2>
          <ul>
            {posts.map(({ id, title }) => (
              <li key={id}>
                <h3>{title}</h3>
              </li>
            ))}
          </ul>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
